name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  scan:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./
          framework: terraform 

  terraform:
   # needs: scan
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_TCS }}'

    # Setup Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.4 # Update to the desired Terraform version

    # Initialize Terraform
    #- name: Terraform Init
    #  run: terraform init
    #  working-directory: ./path/to/terraform/files

    # Validate the Terraform code
    #- name: Terraform Validate
    #  run: terraform validate
     # working-directory: ./path/to/terraform/files

    # Plan Terraform changes
    - name: Terraform destroy
      run: terraform destroy
    #  working-directory: ./path/to/terraform/files

    # Apply Terraform changes (only on push to main)
    #- name: Terraform Apply
    #  if: github.ref == 'refs/heads/main'
     # run: terraform apply -auto-approve
     # working-directory: ./path/to/terraform/files
     # env:
     #   GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
